# Generated by Django 6.0.5 on 2026-06-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField()),
                ('age', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('Adult', 'Adult'), ('Children', 'Children')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('level_of_education', models.CharField(max_length=100)),
                ('program', models.CharField(choices=[('ICT', 'ICT'), ('Computer for Beginners', 'Computer for Beginners'), ('Computer Graphics', 'Computer Graphics'), ('Plumbing', 'Plumbing'), ('Electrical Electronics', 'Electrical Electronics'), ('Solar System Installation', 'Solar System Installation'), ('Alamaco & Aluminium Works', 'Alamaco & Aluminium Works')], max_length=100)),
                ('duration', models.CharField(choices=[('3 months', '3 months'), ('6 months', '6 months'), ('1 year', '1 year')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('guardian_name', models.CharField(blank=True, max_length=100)),
                ('guardian_address', models.TextField(blank=True)),
                ('guardian_phone_number', models.CharField(blank=True, max_length=20)),
                ('student_passport', models.ImageField(blank=True, null=True, upload_to='passports/students/')),
                ('guardian_passport', models.ImageField(blank=True, null=True, upload_to='passports/guardians/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
