# Generated by Django 6.0.5 on 2026-06-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingapplication',
            name='admin_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
