# Generated by Django 6.0.5 on 2026-06-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_trainingapplication_admin_notes_adminactivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingapplication',
            name='guardian_passport',
            field=models.ImageField(default='placeholder.png', upload_to='passports/guardians/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainingapplication',
            name='student_passport',
            field=models.ImageField(default='placeholder.png', upload_to='passports/students/'),
            preserve_default=False,
        ),
    ]
